server:
  port: 8080

spring:
  application:
    name: oidc-idp

  data.redis:
    client-type: jedis
    database: 5
    host: production
    port: 6379
    username: '************'
    password: '************'
    jedis.pool:
      max-active: 100
      max-idle: 15

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  session:
    timeout: 5d
    redis:
      flush-mode: on_save
      namespace: "passport"
      save-mode: on_set_attribute
      repository-type: indexed
      cleanup-cron: 0 * * * * *
      configure-action: notify_keyspace_events

  liquibase:
    contexts: production
    change-log: migration/master.yaml
    enabled: true

  graphql:
    graphiql:
      enabled: false
      path: /graphiql

oidc:
  idp:
    url: http://localhost:${server.port}

logging:
  level:
    root: warn

--- # spring development envs

spring:
  config:
    activate:
      on-profile: development

  graphql:
    graphiql:
      enabled: true

  data.redis:
    client-type: jedis
    database: 5
    host: localhost
    port: 6379
    username: default
    password: testpassword
    jedis.pool:
      max-active: 60
      max-idle: 10

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  liquibase:
    contexts: development
    change-log: migration/master.yaml
    enabled: true

  h2:
    console:
      enabled: true
      path: /h2-console
